"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";

export default function LoginPage(){
  const [mode,setMode]=useState<"login"|"register"|"recover">("login"); const [notice,setNotice]=useState("");
  function demo(e:FormEvent){e.preventDefault();localStorage.setItem("volta-demo-session",JSON.stringify({userId:"demo-maria",name:"Maria",createdAt:new Date().toISOString()}));if(!localStorage.getItem("volta-demo-access"))localStorage.setItem("volta-demo-access",JSON.stringify(["mapa","sos","desafio","jornada"]));location.href="/app"}
  return <main className="auth-shell"><section className="auth-brand-panel"><Link href="/" className="brand brand-light"><span className="brand-mark">V</span><span>Volta Pra <em>Você</em></span></Link><div><span className="eyebrow light">Seu espaço diário</span><h1>Voltar para si também pode começar por aqui.</h1><p>Suas missões, check-ins, registros e pequenas vitórias reunidos em um espaço privado.</p></div><blockquote>“Hoje você não precisa mudar tudo. Precisa apenas não se abandonar.”</blockquote></section><section className="auth-form-panel"><div className="auth-box"><Link href="/" className="mobile-auth-brand">← Voltar ao início</Link><div className="auth-tabs"><button className={mode==="login"?"active":""} onClick={()=>setMode("login")}>Entrar</button><button className={mode==="register"?"active":""} onClick={()=>setMode("register")}>Criar conta</button></div>{mode==="login"&&<><h2>Que bom ter você de volta.</h2><p>Entre para continuar de onde parou.</p><form onSubmit={demo}><label>E-mail<input type="email" required defaultValue="maria@demo.volta"/></label><label>Senha<input type="password" required defaultValue="VoltaDemo#2026"/></label><button type="button" className="forgot-link" onClick={()=>setMode("recover")}>Esqueci minha senha</button><button className="button">Entrar na conta de demonstração</button></form><div className="auth-divider"><span>ou</span></div><a href="/signin-with-chatgpt?return_to=%2Fapp" className="chatgpt-button">Continuar com ChatGPT</a></>}{mode==="register"&&<><h2>Crie seu espaço.</h2><p>Na demonstração, sua conta é criada com dados de teste. A publicação usa a identidade segura do ambiente.</p><form onSubmit={demo}><label>Primeiro nome<input required defaultValue="Maria"/></label><label>E-mail<input type="email" required defaultValue="maria@demo.volta"/></label><label>Crie uma senha<input type="password" required defaultValue="VoltaDemo#2026" minLength={8}/></label><label className="check-row"><input type="checkbox" required defaultChecked/><span>Li e aceito os <Link href="/legal#termos">termos e a política de privacidade</Link>.</span></label><button className="button">Criar conta de demonstração</button></form></>}{mode==="recover"&&<><button className="text-button" onClick={()=>setMode("login")}>← Voltar</button><h2>Recuperar acesso.</h2><p>Informe seu e-mail. No modo de demonstração, mostramos a confirmação sem disparar mensagens.</p><form onSubmit={e=>{e.preventDefault();setNotice("Instruções de demonstração geradas. Em produção, o provedor de identidade envia o link seguro.")}}><label>E-mail<input type="email" required defaultValue="maria@demo.volta"/></label><button className="button">Enviar instruções</button></form>{notice&&<p className="success-note">{notice}</p>}</>}<div className="demo-credentials"><strong>Acesso de teste</strong><span>Usuária: maria@demo.volta</span><span>Senha: VoltaDemo#2026</span><Link href="/admin">Ir para administração de teste →</Link></div></div></section></main>
}
