"use client";
/* eslint-disable react-hooks/set-state-in-effect, react-hooks/immutability, jsx-a11y/label-has-associated-control, @typescript-eslint/no-unused-expressions */
import { SafeLink as Link } from "@/components/SafeLink";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { products } from "@/lib/content";

type AdminData={metrics:Record<string,number>;profiles:Array<Record<string,unknown>>;leads:Array<Record<string,unknown>>;reports:Array<Record<string,unknown>>};
const metricLabels:Record<string,string>={leads:"Leads",users:"Usuárias",quizStarted:"Quiz iniciados",quizCompleted:"Quiz concluídos",completionRate:"Conclusão",revenue:"Receita teste",ticket:"Ticket médio",missions:"Missões concluídas",activeUsers:"Ativas em 7 dias",retention:"Retenção",cancellations:"Cancelamentos"};

export default function AdminPage(){
  const [allowed,setAllowed]=useState(false),[error,setError]=useState(""),[section,setSection]=useState("dashboard"),[data,setData]=useState<AdminData|null>(null),[search,setSearch]=useState("");
  useEffect(()=>{if(sessionStorage.getItem("volta-admin")==="ok"){setAllowed(true);load()}},[]);
  async function load(){const r=await fetch("/api/data?mode=admin&userId=demo-admin",{cache:"no-store"});if(r.ok)setData(await r.json())}
  function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);if(fd.get("email")==="admin@demo.volta"&&fd.get("password")==="AdminVolta#2026"){sessionStorage.setItem("volta-admin","ok");setAllowed(true);load()}else setError("Credenciais de demonstração inválidas.")}
  if(!allowed)return <main className="admin-login"><Link href="/" className="brand"><span className="brand-mark">V</span><span>Volta Pra <em>Você</em></span></Link><form onSubmit={login}><span className="eyebrow">Acesso protegido</span><h1>Painel administrativo</h1><p>Use as credenciais de demonstração fornecidas abaixo.</p><label>E-mail<input name="email" type="email" defaultValue="admin@demo.volta" required/></label><label>Senha<input name="password" type="password" defaultValue="AdminVolta#2026" required/></label>{error&&<p className="form-error">{error}</p>}<button className="button">Entrar no painel</button><div className="demo-credentials"><strong>Administrador de teste</strong><span>admin@demo.volta</span><span>AdminVolta#2026</span></div></form></main>;
  return <div className="admin-shell"><aside className="admin-sidebar"><Link href="/" className="brand brand-light"><span className="brand-mark">V</span><span>Volta Pra <em>Você</em></span></Link><span className="admin-label">Administração</span><nav>{[["dashboard","Visão geral"],["leads","Leads"],["content","Conteúdo e produtos"],["community","Moderação"],["access","Acessos"],["automation","Automações"]].map(([id,label])=><button key={id} className={section===id?"active":""} onClick={()=>setSection(id)}>{label}</button>)}</nav><Link href="/app">Ver área da usuária →</Link><button className="admin-exit" onClick={()=>{sessionStorage.removeItem("volta-admin");location.reload()}}>Sair</button></aside><main className="admin-main"><header><div><span className="eyebrow">Painel administrativo</span><h1>{section==="dashboard"?"Visão geral":section==="leads"?"Gestão de leads":section==="content"?"Conteúdo e produtos":section==="community"?"Moderação da comunidade":section==="access"?"Controle de acessos":"Automações"}</h1></div><div className="admin-user"><span>A</span><div><strong>Administradora</strong><small>Ambiente de teste</small></div></div></header>{!data?<div className="app-loading"><i/><p>Carregando indicadores…</p></div>:<>{section==="dashboard"&&<Dashboard data={data}/>} {section==="leads"&&<Leads data={data} search={search} setSearch={setSearch}/>} {section==="content"&&<Content/>} {section==="community"&&<Moderation data={data}/>} {section==="access"&&<AccessControl/>} {section==="automation"&&<Automations/>}</>}</main></div>
}

function Dashboard({data}:{data:AdminData}){return <div className="admin-view"><div className="metric-grid">{Object.entries(data.metrics).map(([key,value])=><article key={key}><span>{metricLabels[key]??key}</span><strong>{key==="revenue"||key==="ticket"?`R$ ${value.toLocaleString("pt-BR",{minimumFractionDigits:2})}`:key==="completionRate"||key==="retention"?`${value}%`:value}</strong><small>{key==="leads"?"capturados no diagnóstico":key==="revenue"?"compras simuladas":"dados atualizados"}</small></article>)}</div><div className="admin-charts"><article><div className="section-title-row"><div><span className="eyebrow">Funil</span><h2>Do diagnóstico ao acesso</h2></div><span>Ambiente de teste</span></div>{[["Quiz iniciado",data.metrics.quizStarted],["Quiz concluído",data.metrics.quizCompleted],["Lead capturado",data.metrics.leads],["Compra simulada",Math.max(0,Math.round(data.metrics.revenue/17))]].map(([label,value],i)=><div className="funnel-row" key={String(label)}><span>{label}</span><div><i style={{width:`${Math.max(8,100-i*20)}%`}}/></div><strong>{value}</strong></div>)}</article><article><span className="eyebrow">Perfis mais comuns</span><h2>Diagnósticos concluídos</h2>{data.profiles.length?data.profiles.map((p,i)=><div className="profile-stat" key={String(p.profile_key)}><span>{i+1}</span><p>{String(p.profile_key||"Sem perfil")}</p><strong>{String(p.total)}</strong></div>):<div className="empty-state compact"><p>Os perfis aparecerão após os primeiros diagnósticos.</p></div>}</article></div><div className="admin-note"><strong>Privacidade por padrão</strong><p>O painel não exibe textos do diário privado. Administradores veem apenas métricas agregadas e dados operacionais autorizados.</p></div></div>}

function Leads({data,search,setSearch}:{data:AdminData;search:string;setSearch:(s:string)=>void}){const filtered=useMemo(()=>data.leads.filter(l=>`${l.name} ${l.email} ${l.profile_id}`.toLowerCase().includes(search.toLowerCase())),[data,search]);function csv(){const rows=[["Nome","E-mail","WhatsApp","Perfil","Pontuação","Consentimento","Data"],...filtered.map(l=>[l.name,l.email,l.phone,l.profile_id,l.score,l.marketing_consent?"sim":"não",l.created_at])];const blob=new Blob([rows.map(r=>r.map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")).join("\n")],{type:"text/csv;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="leads-volta.csv";a.click()}return <div className="admin-view"><div className="table-tools"><label>Buscar lead<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Nome, e-mail ou perfil"/></label><button className="button button-secondary" onClick={csv}>Exportar CSV</button></div><div className="data-table"><table><thead><tr><th>Nome</th><th>Contato</th><th>Perfil</th><th>Pontuação</th><th>Marketing</th><th>Data</th><th>Status</th></tr></thead><tbody>{filtered.map(l=><tr key={String(l.id)}><td><strong>{String(l.name)}</strong></td><td>{String(l.email)}<small>{String(l.phone)}</small></td><td>{String(l.profile_id)}</td><td>{String(l.score)}/100</td><td>{l.marketing_consent?"Consentiu":"Não consentiu"}</td><td>{new Date(String(l.created_at)).toLocaleDateString("pt-BR")}</td><td><span className="status-pill">{String(l.status)}</span></td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state compact"><p>Nenhum lead encontrado.</p></div>}</div></div>}

function Content(){const [items,setItems]=useState(products),[saved,setSaved]=useState("");return <div className="admin-view"><div className="section-title-row"><div><span className="eyebrow">Produtos e ofertas</span><h2>Textos e preços configuráveis</h2></div><button className="button" onClick={()=>{localStorage.setItem("volta-admin-products",JSON.stringify(items));setSaved("Alterações de demonstração salvas.");setTimeout(()=>setSaved(""),2500)}}>Salvar alterações</button></div>{saved&&<p className="success-note">{saved}</p>}<div className="product-editor">{items.map((p,i)=><article key={p.id}><span>{p.id}</span><label>Nome<input value={p.name} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,name:e.target.value}:x))}/></label><label>Preço<input type="number" value={p.price} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,price:Number(e.target.value)}:x))}/></label><label>Entregáveis<textarea value={p.access} onChange={e=>setItems(items.map((x,j)=>j===i?{...x,access:e.target.value}:x))}/></label><label className="check-row"><input type="checkbox" defaultChecked/><span>Produto ativo</span></label></article>)}</div><div className="content-catalog"><h3>Outros conteúdos preparados para edição</h3>{["Perguntas do quiz","Perfis de resultado","Missões e cartas","Perguntas do diário","Respostas SOS","Páginas e textos","FAQ e termos","Conquistas"].map(i=><button key={i} onClick={()=>alert(`${i}: editor preparado para a integração editorial final.`)}>{i}<span>Editar →</span></button>)}</div></div>}

function Moderation({data}:{data:AdminData}){const [reports,setReports]=useState(data.reports);return <div className="admin-view"><div className="moderation-cards"><article><strong>{reports.filter(r=>r.status==="open").length}</strong><span>denúncias abertas</span></article><article><strong>12</strong><span>palavras bloqueadas</span></article><article><strong>0</strong><span>usuárias suspensas</span></article></div><div className="moderation-list"><h2>Fila de revisão</h2>{reports.length?reports.map(r=><article key={String(r.id)}><div><span className="status-pill">{String(r.status)}</span><small>{new Date(String(r.created_at)).toLocaleDateString("pt-BR")}</small></div><p>“{String(r.body||"Publicação removida")}”</p><strong>Motivo: {String(r.reason)}</strong><div><button onClick={()=>setReports(reports.map(x=>x.id===r.id?{...x,status:"resolved"}:x))}>Manter conteúdo</button><button className="danger" onClick={()=>setReports(reports.map(x=>x.id===r.id?{...x,status:"removed"}:x))}>Remover conteúdo</button></div></article>):<div className="empty-state compact"><p>Nenhuma denúncia aguardando revisão.</p></div>}</div><div className="rules-admin"><h3>Regras ativas</h3><p>Diagnósticos · orientação médica · assédio · ódio · dados pessoais · spam · promessas financeiras · julgamento de aparência · conteúdo sexual · comportamentos perigosos</p><button onClick={()=>alert("A lista de palavras bloqueadas será editada aqui na integração editorial.")}>Editar palavras bloqueadas</button></div></div>}

function AccessControl(){const [email,setEmail]=useState("maria@demo.volta"),[granted,setGranted]=useState<string[]>(["mapa","sos","desafio","jornada"]),[notice,setNotice]=useState("");return <div className="admin-view"><div className="access-search"><span className="eyebrow">Localizar usuária</span><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="button button-secondary" onClick={()=>setNotice(`Acessos de ${email} carregados.`)}>Buscar</button></div>{notice&&<p className="success-note">{notice}</p>}<div className="access-admin-card"><div className="admin-user-large"><span>M</span><div><strong>Maria</strong><small>{email}</small><p>Entrada: {new Date().toLocaleDateString("pt-BR")}</p></div></div><div>{products.map(p=><label key={p.id}><span><strong>{p.name}</strong><small>R$ {p.price}</small></span><input type="checkbox" checked={granted.includes(p.id)} onChange={e=>setGranted(e.target.checked?[...granted,p.id]:granted.filter(id=>id!==p.id))}/></label>)}</div><button className="button" onClick={()=>{localStorage.setItem("volta-demo-access",JSON.stringify(granted));setNotice("Permissões da demonstração atualizadas.")}}>Atualizar permissões</button></div><div className="audit-preview"><h3>Histórico de acesso</h3><p><span>Hoje</span>Acessos revisados pela administradora de demonstração.</p><p><span>Hoje</span>Jornada VOLTA liberada por compra simulada.</p></div></div>}

function Automations(){const names=["Abandono do quiz","Conclusão do diagnóstico","Mensagem com resultado","Boas-vindas","Lembrete de missão","Aviso de sequência","Marco de sete dias","Convite à Jornada","Recuperação de checkout","Convite à comunidade","Relatório semanal"];const [enabled,setEnabled]=useState<Set<string>>(new Set(["Boas-vindas","Mensagem com resultado"]));return <div className="admin-view"><div className="admin-note"><strong>Consentimento obrigatório</strong><p>Nenhuma automação realiza disparos nesta demonstração. A estrutura respeita o consentimento de marketing e pode ser ativada individualmente após conectar um provedor.</p></div><div className="automation-list">{names.map(name=><label key={name}><span><strong>{name}</strong><small>{enabled.has(name)?"Configurada, sem disparo real":"Desativada"}</small></span><input type="checkbox" checked={enabled.has(name)} onChange={e=>{const next=new Set(enabled);e.target.checked?next.add(name):next.delete(name);setEnabled(next)}}/></label>)}</div><button className="button" onClick={()=>localStorage.setItem("volta-automations",JSON.stringify([...enabled]))}>Salvar configurações</button></div>}
