"use client";
/* eslint-disable react-hooks/set-state-in-effect, no-empty, jsx-a11y/label-has-associated-control */

import { SafeLink as Link } from "@/components/SafeLink";
import { useEffect, useMemo, useState } from "react";
import { ProfileKey, profileContent } from "@/lib/content";

type StoredResult={name:string;profile:ProfileKey;score:number;areas:Record<string,number>;weight:string;desired:string;leadId?:string};
const fallback:StoredResult={name:"Maria",profile:"sobrecarregada",score:76,weight:"Trabalho",desired:"Tempo para mim",areas:{"Tempo pessoal":82,"Energia":74,"Limites":88,"Projetos":61,"Vida social":55,"Organização":72,"Descanso":79,"Autocuidado":67}};

export function ResultPage(){
  const [data,setData]=useState<StoredResult>(fallback); const [bump,setBump]=useState(false); const [buying,setBuying]=useState(false); const [notice,setNotice]=useState("");
  useEffect(()=>{const raw=localStorage.getItem("volta-result");if(raw)try{setData(JSON.parse(raw))}catch{}},[]);
  const profile=profileContent[data.profile]??profileContent.sobrecarregada;
  const weakest=useMemo(()=>Object.entries(data.areas??{}).sort((a,b)=>b[1]-a[1])[0]?.[0]??"Tempo pessoal",[data]);
  const strongest=useMemo(()=>Object.entries(data.areas??{}).sort((a,b)=>a[1]-b[1])[0]?.[0]??"Projetos",[data]);
  async function purchase(){setBuying(true);setNotice("");const products=bump?["mapa","sos"]:["mapa"];try{const response=await fetch("/api/data",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"purchase",userId:"demo-maria",leadId:data.leadId,products})});if(!response.ok)throw new Error();localStorage.setItem("volta-demo-access",JSON.stringify(products));window.location.href="/upsell"}catch{setNotice("Não foi possível concluir a simulação agora. Tente novamente.");setBuying(false)}}
  return <main className="result-shell">
    <header className="result-header"><Link href="/" className="brand"><span className="brand-mark">V</span><span>Volta Pra <em>Você</em></span></Link><span className="private-pill">Diagnóstico privado</span></header>
    <section className="result-hero"><div><span className="eyebrow">Seu diagnóstico</span><h1>{data.name}, seu perfil é<br/><em>{profile.name}.</em></h1><p>{profile.message}</p></div><div className="score-ring" style={{"--score":`${data.score*3.6}deg`} as React.CSSProperties}><div><strong>{data.score}</strong><span>de 100</span></div></div></section>
    <section className="result-grid"><article className="result-summary"><span className="eyebrow">O que seu resultado mostra</span><h2>{profile.description}</h2><div className="pattern-list"><p><span>Área mais afetada</span><strong>{weakest}</strong></p><p><span>O que mais pesa hoje</span><strong>{data.weight}</strong></p><p><span>Maior potencial de avanço</span><strong>{data.desired||strongest}</strong></p></div></article><article className="area-chart"><div className="chart-head"><div><span className="eyebrow">Seu mapa atual</span><h2>O espaço que cada área pede</h2></div><span>mais atenção →</span></div>{Object.entries(data.areas??fallback.areas).map(([name,value])=><div className="chart-row" key={name}><span>{name}</span><div><i style={{width:`${Math.max(8,value)}%`}}/></div><strong>{value}</strong></div>)}<small>Este gráfico organiza suas respostas. Não é um diagnóstico médico ou psicológico.</small></article></section>
    <section className="first-plan"><div><span className="eyebrow light">Seu primeiro plano</span><h2>Três passos para começar sem mudar tudo.</h2></div><ol><li><span>1</span><div><strong>Nomeie o que pesa</strong><p>Anote as três responsabilidades que mais ocupam sua cabeça.</p></div></li><li><span>2</span><div><strong>Proteja 15 minutos</strong><p>Escolha amanhã um pequeno espaço com começo e fim.</p></div></li><li><span>3</span><div><strong>Reduza uma etapa</strong><p>Simplifique uma tarefa que você repete por hábito.</p></div></li></ol></section>
    <section className="offer-section"><div className="offer-copy"><span className="offer-tag">Próximo passo recomendado</span><span className="eyebrow">Mapa da Volta</span><h2>Transforme este resultado em sete dias de ação.</h2><p>Descubra em quais áreas você mais se deixou para depois e receba um plano prático para começar sua retomada.</p><ul><li>Diagnóstico completo e mapa das 8 áreas</li><li>Plano personalizado de 7 dias</li><li>Uma missão curta por dia</li><li>Checklist e diário guiado</li><li>Relatório final no celular</li></ul></div><div className="checkout-card"><span className="test-badge">Modo de compra simulada</span><p>Mapa da Volta</p><div className="price"><small>R$</small><strong>17</strong><small>,00</small></div><label className="order-bump"><input type="checkbox" checked={bump} onChange={e=>setBump(e.target.checked)}/><span><b>Quero adicionar o Kit SOS</b><small>Respostas práticas para dias difíceis por R$ 27.</small></span></label><div className="total"><span>Total de teste</span><strong>R$ {bump?"44":"17"},00</strong></div>{notice&&<p className="form-error">{notice}</p>}<button className="button" onClick={purchase} disabled={buying}>{buying?"Liberando seu acesso…":"Quero começar por R$ 17"}</button><p className="secure-note">✓ Sem cobrança real nesta demonstração<br/>✓ Acesso liberado imediatamente</p></div></section>
    <footer className="result-footer"><Link href="/legal#privacidade">Privacidade</Link><span>•</span><Link href="/legal#saude">Aviso de cuidado</Link><span>•</span><Link href="/quiz">Refazer diagnóstico</Link></footer>
  </main>;
}
